FROM nexus3.o-ran-sc.org:10002/o-ran-sc/bldr-ubuntu20-c-go:1.0.0

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ='Asia/Kolkata'
ADD . /opt/o-du-l2
WORKDIR /opt/o-du-l2

RUN apt-get update && \
    apt-get install -y \
    git \
    vim \
    iputils-ping \
    net-tools \
    iproute2 \
    termshark \
    tcpdump \
    && apt-get clean


RUN apt-get update && apt-get install -y libpcap-dev



#CMD /opt/o-du-l2/bin/cu_stub/cu_stub
